dataset_name: "heart_1k_v3_fastq"
sample_file: "examples/heart_1k_v3_fastq/sample_sheet.csv"
cell_annots: "examples/heart_1k_v3_fastq/annots.csv"
target: "utrome_mm10_v2"

bx_whitelist: "extdata/bxs/3M-february-2018.txt"
tech: "10xv3"
strand: "--fr-stranded"

min_umis: 1000
