dataset_name: "output"
sample_regex: ".*"
cell_annots: null
cell_annots_key: "cell_id"
target: "utrome_mm10_v1"
output_type:
  - "txs"
  - "genes"
tmp_dir: "/tmp"
bx_whitelist: null
correct_bus: True
min_umis: 500
targets_config: "extdata/targets/targets.yaml"
