tmp_dir:
  "/tmp"

genome:
  "mm10"

utrome_gtf:
  "extdata/gff/adult.utrome.e3.t200.f0.999.w500.gtf"

utrome_kdx:
  "extdata/kallisto/adult.utrome.e3.t200.f0.999.w500.kdx"

utrome_merge:
  "extdata/gff/adult.utrome.e3.t200.f0.999.w500.merge.tsv"

atlas_txs:
  "extdata/atlas/utrome_txs_annotation.Rds"

atlas_genes:
  "extdata/atlas/utrome_genes_annotation.Rds"

sample_regex:
  ".*"

final_output_file:
  "data/sce/output.utrome.txs.Rds"

bx_whitelist:
  ""

annotation_file:
  ""

correct_bus:
  True

min_umis:
  500
