sample_file:
  "examples/neuron_1k_v2_bam/sample_sheet.csv"

annotation_file:
  "examples/neuron_1k_v2_bam/annots.csv"

bx_whitelist:
  "extdata/bxs/737K-august-2016.txt"

final_output_file:
  "data/sce/neuron_1k_v2_bam.utrome.txs.Rds"

tech:
  "10xv2"

strand:
  "--fr-stranded"

min_umis:
  1000
