dataset_name: "neuron_1k_v2_bam"
sample_file: "examples/neuron_1k_v2_bam/sample_sheet.csv"
cell_annots: "examples/neuron_1k_v2_bam/annots.csv"
target: "utrome_mm10_v2"

bx_whitelist: "extdata/bxs/737K-august-2016.txt"
tech: "10xv2"
strand: "--fr-stranded"

min_umis: 1000
