dataset_name:
  "neuron_10k_v3_fastq"

sample_file:
  "examples/neuron_10k_v3_fastq/sample_sheet.csv"

annotation_file:
  "examples/neuron_10k_v3_fastq/annots.csv"

bx_whitelist:
  "extdata/bxs/3M-february-2018.txt"

tech:
  "10xv3"

strand:
  "--fr-stranded"

min_umis:
  1000
