dataset_name:
  "neuron_1k_v3_bam"

sample_file:
  "examples/neuron_1k_v3_bam/sample_sheet.csv"

annotation_file:
  "examples/neuron_1k_v3_bam/annots.csv"

bx_whitelist:
  "extdata/bxs/3M-february-2018.txt"

tech:
  "10xv3"

strand:
  "--fr-stranded"

min_umis:
  1000
