dataset_name: "neuron_1k_v3_bam"
sample_file: "examples/neuron_1k_v3_bam/sample_sheet.csv"
cell_annots: "examples/neuron_1k_v3_bam/annots.csv"
target: "utrome_mm10_v2"

bx_whitelist: "extdata/bxs/3M-february-2018.txt"
tech: "10xv3"
strand: "--fr-stranded"

min_umis: 1000
