sample_file:
  "examples/heart_1k_v2_fastq/sample_sheet.csv"

annotation_file:
  "examples/heart_1k_v2_fastq/annots.csv"

bx_whitelist:
  "extdata/bxs/737K-august-2016.txt"

final_output_file:
  "data/sce/heart_1k_v2_fastq.utrome.txs.Rds"

tech:
  "10xv2"

strand:
  "--fr-stranded"
